<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-01T08:19:04 PET" name="Maddison Suite" finished-at="2023-07-01T08:19:17 PET" duration-ms="12805">
    <groups>
    </groups>
    <test started-at="2023-07-01T08:19:04 PET" name="Login Test" finished-at="2023-07-01T08:19:17 PET" duration-ms="12805">
      <class name="com.maddison.tests.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.maddison.tests.LoginTest@1fb19a0]" started-at="2023-07-01T08:19:04 PET" name="setup" finished-at="2023-07-01T08:19:06 PET" duration-ms="2119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="initialMethods()[pri:0, instance:com.maddison.tests.LoginTest@1fb19a0]" started-at="2023-07-01T08:19:06 PET" name="initialMethods" finished-at="2023-07-01T08:19:12 PET" duration-ms="5533" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialMethods -->
        <test-method signature="logOut(java.lang.reflect.Method)[pri:0, instance:com.maddison.tests.LoginTest@1fb19a0]" started-at="2023-07-01T08:19:12 PET" name="logOut" finished-at="2023-07-01T08:19:12 PET" duration-ms="106" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.maddison.tests.LoginTest.logOut(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOut -->
        <test-method is-config="true" signature="initialMethods()[pri:0, instance:com.maddison.tests.LoginTest@1fb19a0]" started-at="2023-07-01T08:19:12 PET" name="initialMethods" finished-at="2023-07-01T08:19:12 PET" duration-ms="586" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialMethods -->
        <test-method retried="true" signature="singIn(java.lang.reflect.Method)[pri:0, instance:com.maddison.tests.LoginTest@1fb19a0]" started-at="2023-07-01T08:19:12 PET" name="singIn" finished-at="2023-07-01T08:19:14 PET" duration-ms="1370" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.maddison.tests.LoginTest.singIn(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account] but found [Customer Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account] but found [Customer Login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.maddison.pages.AccountPage.verifyLogin(AccountPage.java:42)
at com.maddison.tests.LoginTest.singIn(LoginTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- singIn -->
        <test-method is-config="true" signature="initialMethods()[pri:0, instance:com.maddison.tests.LoginTest@1fb19a0]" started-at="2023-07-01T08:19:14 PET" name="initialMethods" finished-at="2023-07-01T08:19:15 PET" duration-ms="1031" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialMethods -->
        <test-method signature="singIn(java.lang.reflect.Method)[pri:0, instance:com.maddison.tests.LoginTest@1fb19a0]" started-at="2023-07-01T08:19:15 PET" name="singIn" finished-at="2023-07-01T08:19:16 PET" duration-ms="1127" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.maddison.tests.LoginTest.singIn(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account] but found [Customer Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account] but found [Customer Login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.maddison.pages.AccountPage.verifyLogin(AccountPage.java:42)
at com.maddison.tests.LoginTest.singIn(LoginTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- singIn -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.maddison.tests.LoginTest@1fb19a0]" started-at="2023-07-01T08:19:16 PET" name="teardown" finished-at="2023-07-01T08:19:17 PET" duration-ms="440" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.maddison.tests.LoginTest -->
    </test> <!-- Login Test -->
  </suite> <!-- Maddison Suite -->
</testng-results>
